### ISSUE TITLE
Enable sending headers via the built in "request" command

### ISSUE THREAD

**Issue by zealsprince** [Mavulp/frippy#2]
Currently it is not possible to send headers when making a request via the built-in request command. This means API keys and other relevant information can not be sent.

https://github.com/Mavulp/frippy/blob/dev/src/plugins/factoid/utils.rs#L20-L37

I would like to expand this function to include an optional header parameter. Additionally it should return more information as well.

Stretch goal: add further request types to align with REST.

**Comment by Jokler** [comment]
Headers, method and body can now be set in this way:
```lua
request("https://example.com", {method = "POST", headers = {key = "value"}, body = "content"})
```
